/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: rautkrutant055 (https://sketchfab.com/rautkrutant055)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-chessboard-0b36f04aeead43f296ad97c6763cac41
Title: Classic Chessboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Board_Board_0.geometry} material={materials.Board} position={[-5.28, 9.18, 6.25]} rotation={[-Math.PI / 2, 0, 0]} scale={580.52} />
          <mesh geometry={nodes.Plane005_Black_0.geometry} material={materials.Black} position={[-18.59, 10.11, 98.46]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={543.89} />
          <mesh geometry={nodes.Plane006_Black_0.geometry} material={materials.Black} position={[7.96, 10.11, 98.46]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={543.85} />
          <mesh geometry={nodes.WhiteHorsePiece004_Black_0.geometry} material={materials.Black} position={[-71.03, 10.11, 98.46]} rotation={[Math.PI, 0, -Math.PI]} scale={[122.66, 115.69, 122.66]} />
          <mesh geometry={nodes.WhiteHorsePiece005_Black_0.geometry} material={materials.Black} position={[60.44, 10.11, 98.46]} rotation={[Math.PI, 0, -Math.PI]} scale={[122.66, 115.69, 122.66]} />
          <mesh geometry={nodes.WhitePawnPiece4006_Black_0.geometry} material={materials.Black} position={[-97.28, 10.11, 72.18]} rotation={[Math.PI, 0, -Math.PI]} scale={122.66} />
          <mesh geometry={nodes.WhitePawnPiece4013_Black_0.geometry} material={materials.Black} position={[87.31, 10.11, 98.46]} rotation={[Math.PI, 0, -Math.PI]} scale={143.92} />
          <mesh geometry={nodes.WhitePawnPiece4014_Black_0.geometry} material={materials.Black} position={[34.12, 10.11, 98.46]} rotation={[Math.PI, 0, -Math.PI]} scale={143.92} />
          <mesh geometry={nodes.WhitePawnPiece4015_Black_0.geometry} material={materials.Black} position={[-97.89, 10.11, 98.46]} rotation={[Math.PI, 0, -Math.PI]} scale={143.92} />
          <mesh geometry={nodes.WhitePawnPiece4016_Black_0.geometry} material={materials.Black} position={[-44.71, 10.11, 98.46]} rotation={[Math.PI, 0, -Math.PI]} scale={143.92} />
          <mesh geometry={nodes.Plane001_White_0.geometry} material={materials.White} position={[8.02, 10.11, -85.98]} rotation={[-Math.PI / 2, 0, 0]} scale={543.89} />
          <mesh geometry={nodes.Plane002_White_0.geometry} material={materials.White} position={[-18.53, 10.11, -85.98]} rotation={[-Math.PI / 2, 0, 0]} scale={543.85} />
          <mesh geometry={nodes.WhiteHorsePiece_White_0.geometry} material={materials.White} position={[60.45, 10.11, -85.98]} scale={[122.66, 115.69, 122.66]} />
          <mesh geometry={nodes.WhiteHorsePiece003_White_0.geometry} material={materials.White} position={[-71.01, 10.11, -85.98]} scale={[122.66, 115.69, 122.66]} />
          <mesh geometry={nodes.WhitePawnPiece4_White_0.geometry} material={materials.White} position={[87.26, 10.11, -59.7]} scale={122.66} />
          <mesh geometry={nodes.WhitePawnPiece4001_White_0.geometry} material={materials.White} position={[-97.88, 10.11, -85.98]} scale={143.92} />
          <mesh geometry={nodes.WhitePawnPiece4003_White_0.geometry} material={materials.White} position={[-44.7, 10.11, -85.98]} scale={143.92} />
          <mesh geometry={nodes.WhitePawnPiece4008_White_0.geometry} material={materials.White} position={[87.32, 10.11, -85.98]} scale={143.92} />
          <mesh geometry={nodes.WhitePawnPiece4009_White_0.geometry} material={materials.White} position={[34.14, 10.11, -85.98]} scale={143.92} />
        </group>
      </group>
    </group>
  )
}

export default Model

useGLTF.preload('/scene.gltf')
